name: train
run_id: commands[0]
env COMSPEC: C:\Windows\system32\cmd.exe
env NUMBER_OF_PROCESSORS: 8
env PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
env PROCESSOR_ARCHITECTURE: AMD64
env PROGRAMDATA: C:\ProgramData
env PROGRAMFILES: C:\Program Files
env PROGRAMFILES(X86): C:\Program Files (x86)
env SYSTEMDRIVE: C:
env SYSTEMROOT: C:\Windows
env TEMP: C:\Users\dhava\AppData\Local\Temp
env TMP: C:\Users\dhava\AppData\Local\Temp
env USERPROFILE: C:\Users\dhava
env PATH: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\.tox\test_package\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\dhava\AppData\Local\Programs\Python\Python310;C:\Users\dhava\AppData\Local\Programs\Python\Python310\Scripts;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Users\dhava\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\dhava\AppData\Local\Programs\Python\Python39\;C:\Users\dhava\AppData\Local\Microsoft\WindowsApps
env PYTHONHASHSEED: 431
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TOX_ENV_NAME: train
env TOX_WORK_DIR: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\.tox
env TOX_ENV_DIR: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\.tox\test_package
env VIRTUAL_ENV: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\.tox\test_package
env COLUMNS: 120
env LINES: 30
metadata pid: 12272
cwd: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production
allow: E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\.tox\test_package\Scripts\*
cmd: python lr_model/train.py
exit_code: 1
_config:app_config=AppConfig(training_data_file='data/snli_1.0_train_subset.jsonl', test_data_file='data/snli_1.0_test.jsonl', sample_test_file='data/snli_1.0_sample_test.jsonl', sentence1_vectorizer='data/feature_s1_v1.pkl', sentence2_vectorizer='data/feature_s2_v1.pkl')
app_config=AppConfig(training_data_file='data/snli_1.0_train_subset.jsonl', test_data_file='data/snli_1.0_test.jsonl', sample_test_file='data/snli_1.0_sample_test.jsonl', sentence1_vectorizer='data/feature_s1_v1.pkl', sentence2_vectorizer='data/feature_s2_v1.pkl')

standard error:
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dhava/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\dhava/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\dhava/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\lr_model\train.py", line 41, in <module>
    run_training()
  File "E:\IISC\Second_sem\DL\project\Git_Repo\Natural_Language_Inference_production\lr_model\train.py", line 35, in run_training
    model = LogisticRegression(max_iter=config.model_config.max_iterations)
AttributeError: 'dict' object has no attribute 'max_iterations'
